=== VladimirVasyukov/Web_Chat/src/main/resources/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.com/chat/users"
        xmlns:tns="http://www.epam.com/chat/users"
        elementFormDefault="qualified">

    <complexType name="User">
        <sequence>
            <element name="nick" type="string"/>
            <element name="role" type="tns:Role"/>
        </sequence>
    </complexType>

    <simpleType name="Role">
        <restriction base="string">
            <enumeration value="ADMIN"/>
            <enumeration value="USER"/>
        </restriction>
    </simpleType>

    <element name="users">
        <complexType>
            <sequence>
                <element name="user"
                         type="tns:User"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

</schema>

=== VladimirVasyukov/Web_Chat/src/main/resources/users.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<users xmlns="http://www.epam.com/chat/users"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.epam.com/chat/users users.xsd">

    <user>
        <nick>Vladimir</nick>
        <role>USER</role>
    </user>

    <user>
        <nick>Olga</nick>
        <role>USER</role>
    </user>

    <user>
        <nick>Administrator</nick>
        <role>ADMIN</role>
    </user>

</users>
